### ISSUE TITLE
Variable haxe.ds.Vector type unable to be used or initialized, returns "unknown variable" error.

### ISSUE THREAD

**Issue by BeastTornado** [YoshiCrafter29/hscript-improved#13]
When initializing a Vector variable, whether using a simple "Vector<Float>" or a specified reference "haxe.ds.Vector<Float>", an "unknown variable" error is returned. My assumption is it is an issue with Abstract types, as maps can have the same issue when referred to with a path reference (ex: "haxe.ds.StringMap".

<img width="846" height="74" alt="Image" src="https://github.com/user-attachments/assets/1522e360-e7d1-4b42-9c74-47819aca32f6" />

<img width="835" height="65" alt="Image" src="https://github.com/user-attachments/assets/c3f496d1-7b12-4e5d-acce-746bc82417ba" />

<img width="677" height="152" alt="Image" src="https://github.com/user-attachments/assets/94fe918c-fe49-4adc-8092-db794a8535a6" />

**Comment by BeastTornado** [comment]
Ok nvm maps also just genuinely don't work at all either

<img width="1167" height="49" alt="Image" src="https://github.com/user-attachments/assets/5474b419-f86c-4dfd-a377-4f06aa7cba40" />

**Comment by Jamextreme140** [comment]
Vector is a full abstract type, because it creates a native fixed-length array depending of the target (ex. `Vector` in C++ uses `cpp.NativeArray`)

On the other hand, I will check about the map thing since StringMap is a class and it should not fail. However, for now I recommend to initialize any map like this:
```haxe
var map:Map<String, Dynamic> = ["" => null];
```

This will create a StringMap based on the key type

**Comment by Jamextreme140** [comment]
Which version of Codename are you using? Legacy or Latest?

**Comment by BeastTornado** [comment]
Latest

**Comment by BeastTornado** [comment]
When initializing the map in the way you had shown, the game crashed.

<img width="834" height="26" alt="Image" src="https://github.com/user-attachments/assets/37a05a1e-0976-4b2d-be4e-70febcdd19bd" />

**Comment by Jamextreme140** [comment]
Ok. Try importing the StringMap class first and then create it. 
```haxe
import haxe.ds.StringMap;

var redRings:StringMap<Dynamic> = new StringMap<Dynamic>() ;
```

I have used the class and it works fine for me.

**Comment by Jamextreme140** [comment]
Once I'm available, I'll check the class path reference thing, ok?

**Comment by BeastTornado** [comment]
When importing the StringMap class I am getting a null function pointer error when attempting to call map functions off of the variable after initialization.

<img width="1115" height="30" alt="Image" src="https://github.com/user-attachments/assets/c7a89917-6ea0-4b7c-9abd-bd7192c68e11" />

**Comment by BeastTornado** [comment]
For reference, this is how it is initialized: 

<img width="523" height="117" alt="Image" src="https://github.com/user-attachments/assets/7edd873b-fbd6-423a-848c-e2b97c7d496a" />

**Comment by Jamextreme140** [comment]
> Latest

Latest GitHub Actions Build or v1.0.1?

**Comment by Jamextreme140** [comment]
I just did some tests, and I fixed the path reference thing. But the StringMap usage works fine for me, and the previous example should work

**Comment by BeastTornado** [comment]
v1.0.1

**Comment by Jamextreme140** [comment]
I see why. Most of the current fixes on HScript has been fixed after V1.0.1, like an issue with `using` feature and more.

I recommend to use the latest GitHub Actions Builds or avoid the `using` until the next version

**Comment by BeastTornado** [comment]
I'm still having the same issues on the newest GitHub Actions Build, no differences

**Comment by Jamextreme140** [comment]
Ok. Unfortunately, I couldn't reproduce the StringMap issue since everything worked fine for me. I tried everything and those issues you faced didn't happen.

<img width="913" height="205" alt="Image" src="https://github.com/user-attachments/assets/ae8d7629-ca88-4a4a-87b5-a6bd25b866f1" />

<img width="684" height="68" alt="Image" src="https://github.com/user-attachments/assets/94c3b1fb-e057-4e63-b8ea-544855a300f2" />

Contact me via Discord (as Jamextreme140) to do a more in-depth follow-up.
